name: Docker Python App CI

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Remove old containers (if any)
        run: |
          CONTAINERS=$(docker ps -aq)
          if [ -n "$CONTAINERS" ]; then
            docker rm -f $CONTAINERS
          fi

      - name: Build Docker image
        run:  
         cd python-github
         docker build -t my-python-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name test-app my-python-app

      - name: Wait for app to start
        run: sleep 5

      - name: Test with curl
        run: curl http://localhost:5000
