name: Manual Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

      version:
        description: 'App version to deploy'
        required: true
        default: 'v1.0.0'
        type: string

      dry_run:
        description: 'Run in dry-run mode?'
        required: false
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show Inputs
        run: |
          echo "Deploying version: ${{ github.event.inputs.version }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Dry run: ${{ github.event.inputs.dry_run }}"
