name: Run Python Flask App

on:
  push:
  workflow_dispatch:  # You can trigger this manually

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd python-github
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask App
        run: |
          cd python-github
          python app.py
